FROM postgres:latest
# As of August 20, 2020, postgres:latest gives us Postgres 12.4. Details:

#FROM postgres:12.3




# Create temporary placeholder directory - example docker volume to share data outside container
RUN mkdir /home/datavolume
RUN date > /home/datavolume/test-file-created-by-postgres-Dockerfile.txt


##
#

