---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "flask-hello-world-1-service"
  namespace: "default"
  labels:
    app: "flask-hello-world-1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "flask-hello-world-1"
  type: "NodePort"
